### ISSUE TITLE
Document using WDS_Shortcode_Admin/Shortcode_Button

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/WDS-Shortcodes#2]
Again, will need to document how to build a shortcode that integrates [Shortcode Button](https://github.com/jtsternberg/Shortcode_Button).

**Comment by JayWood** [comment]
@jtsternberg Documentation is coming along nicely - Working on some example classes of closing and non-closing shortcodes.

**Comment by JayWood** [comment]
Example classes are done.  Hoping I can get some time after work today to do the actual documentation.

**Comment by JayWood** [comment]
For those interested immediately, I created a repo showing how this works temporarily, you can view the basic files here: 
https://github.com/JayWood/wds-plugin-playground/tree/master/includes

They're included using normal plugin classes method using the auto loader here:
https://github.com/JayWood/wds-plugin-playground/blob/master/wds-client-plugin-name.php#L160-L165

**Comment by jtsternberg** [comment]
awesome dude

**Comment by jtsternberg** [comment]
On this example: https://github.com/JayWood/wds-plugin-playground/blob/master/includes/class-test-shortcode-admin.php

We should show how to hook into `"{$shortcode}_shortcode_fields"` to modify attribute output, as well as using the sc_content attribute to add content to the shortcode.

``` php
add_filter( "{$this->shortcode}_shortcode_fields", array( $this, 'filter_shortcode_fields' ), 10, 3 );
```

``` php
    /**
     * @param $field_atts
     * @param Shortcode_Button $sc_instance
     * @param $unmodified
     *
     * @return array
     */
    public function filter_shortcode_attributes( $field_atts, $sc_instance, $unmodified ) {
        // error_log( '$unmodified: '. print_r( $unmodified, true ) );
        // error_log( '$field_atts: '. print_r( $field_atts, true ) );

        // 'file' type field id
        $file_field_id = 'attachment_image';
        if ( isset( $unmodified[ $file_field_id . '_id' ] ) && $unmodified[ $file_field_id . '_id' ] ) {
            $field_atts['image_id'] = $unmodified[ $file_field_id . '_id' ];
        }

        /*
         * If you send back `$field_atts['sc_content']`, and you have 'include_close' set to true,
         * The contents of the shortcode will be set to this value.
         * Example:
         *
         * $field_atts['sc_content'] = 'Some content';
         *
         * // generated shortcode:
         * [yourshortcode ...attributes...]Some content[/yourshortcode]
         */
        return $field_atts;
    }


```

**Comment by JayWood** [comment]
After the edits to the wiki, I think this can be closed.  Please review and let me know https://github.com/WebDevStudios/WDS-Shortcodes/wiki

**Comment by jtsternberg** [comment]
:+1:
