### ISSUE TITLE
Composer: Require CMB2?

### ISSUE THREAD

**Issue by JayWood** [WebDevStudios/WDS-Shortcodes#4]
@jtsternberg Since CMB2 is required for the use of fields in the modal, should we require that in composer or merely document that it is required in the wiki/readme file?

**Comment by jtsternberg** [comment]
Composer

**Comment by JayWood** [comment]
@jtsternberg so I have it setup with composer,but It's created a problem whereas CMB2 will load later than what's needed. The failure is happening at [Shortcode_Button::do_cmb_form()#232](https://github.com/jtsternberg/Shortcode_Button/blob/master/shortcode-button.php#L232)

At this point, I believe the load order is off, since if extending the plugin, everything is happening in the construct of extended plugins.  Looking into this more and will report back eventually.

**Comment by jtsternberg** [comment]
Sorry.. based on [new events](https://make.wordpress.org/plugins/2016/03/01/please-do-not-submit-frameworks/), I think it's best if we use [TGMPA](http://tgmpluginactivation.com/) to suggest inclusion of CMB2. For prior art, [see how Google Analytics Top Content Widget does it](https://github.com/jtsternberg/Google-Analytics-Top-Content-Widget/blob/master/includes/class-ga-top-content.php#L42-L49).

**Comment by tw2113** [comment]
@JayWood @jtsternberg Either of you have thoughts on this error?

```
[RuntimeException]                                                                                                                                            
  Could not scan for classes inside "/.../vendor/webdevstudios/  
  wds-shortcodes/vendor/tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php" which does not appear to be a file nor a folder
```

Trying to revise a plugin to have better Composer usage, and this error is cropping up.
