### ISSUE TITLE
Probably should make a library instead of a plugin.

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/WDS-Shortcodes#6]
This makes much more sense as a library that you bundle than a plugin. We should use [WP Lib Loader](http://jtsternberg.github.io/wp-lib-loader/).

**Comment by modemlooper** [comment]
I bundled it like a lib.

**Comment by jtsternberg** [comment]
@modemlooper what did you do about wds-shortcodes CMB2 dependency?

**Comment by modemlooper** [comment]
I'm including CMB2 in the plugin, its not a repo plugin ;)

**Comment by jtsternberg** [comment]
This is done: https://github.com/WebDevStudios/WDS-Shortcodes/commit/a599fdde00ce819279f29ccf652764a8347c2815

**Comment by jtsternberg** [comment]
@modemlooper please update the bundled version of wds-shortcodes in your plugin. Also, please note the change, and that you can not extend the `WDS_Shortcode_Admin` class before the `'init'` hook. You can see what I mean by viewing this diff of the wds-shortcodes demo plugin: https://github.com/jtsternberg/Cool-Shortcode/commit/135096c42a3ffb08567f214494ca932905bd421e#diff-1
