### ISSUE TITLE
Include close parameter and The wysiwyg

### ISSUE THREAD

**Issue by nonsensecreativity** [WebDevStudios/WDS-Shortcodes#7]
When the `include_close` parameter is enabled a wysiwyg editor will be added to the shortcode modal. The problem is in the modal wysiwyg editor **text tab** there are also the shortcode buttons, When I try to insert the shortcode through the modal wysiwyg editor, it will be inserted into the main post wysiwyg editor.

Since the **visual tab** in the modal wysiwyg editor do not show the shortcode buttons maybe the shortcode buttons in **text tab**  shouldn't it be removed as well?

**Comment by jtsternberg** [comment]
Good catch. I agree, they should be removed from the text tab as well. I'll be happy to accept a PR if you're willing to submit one.
