### ISSUE TITLE
Could not scan for classes inside...

### ISSUE THREAD

**Issue by davidshq** [WebDevStudios/WDS-Shortcodes#9]
Running composer install and getting the same error Michael was getting in Issue #4. Not seeing a resolution to this. Any ideas?  

===

@JayWood @jtsternberg Either of you have thoughts on this error?

```
[RuntimeException]                                                                                                                                            
  Could not scan for classes inside "/.../vendor/webdevstudios/  
  wds-shortcodes/vendor/tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php" which does not appear to be a file nor a folder
```

Trying to revise a plugin to have better Composer usage, and this error is cropping up.

_Originally posted by @tw2113 in https://github.com/WebDevStudios/WDS-Shortcodes/issues/4#issuecomment-410924443_

**Comment by davidshq** [comment]
Found if I go install /vendor/webdevstudios/wds-shortcodes/ and run composer install then go back to the main plugin directory and run composer install again, it works - workaround for the moment, but not sure what is causing the issue in the first place?

**Comment by tw2113** [comment]
That was the same thing I was doing when i first commented etc, but the project that I was using this all on has since ditched TinyMCE integration, and my problem went away.
